### ISSUE TITLE
windows下能跑吗？

### ISSUE THREAD

**Issue by jaoyina** [sub-store-org/Sub-Store#277]
按照步骤安装nodejs，pnpm, 然后install， start，结果出来

Error: Cannot find module './src/utils/migration'
Require stack:
- C:\test\Sub-Store-2.14.198\backend\src\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\test\Sub-Store-2.14.198\backend\src\/main.js:22:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (C:\test\Sub-Store-2.14.198\backend\node_modules\.pnpm\registry.npmmirror.com+pirates@4.0.5\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (C:\test\Sub-Store-2.14.198\backend\node_modules\.pnpm\registry.npmmirror.com+pirates@4.0.5\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\test\\Sub-Store-2.14.198\\backend\\src\\main.js' ]
}

Node.js v20.11.0

感觉是不是系统问题，路径格式不对？

**Comment by xream** [comment]
开发参考 https://github.com/sub-store-org/Sub-Store/issues/258

使用直接用 releases 里的 sub-store.bundle.js 就行
或者查看 https://xream.notion.site/Sub-Store-abe6a96944724dc6a36833d5c9ab7c87

**Comment by xream** [comment]
实验性加入了 esbuild 可以尝试一下 `pnpm run --parallel --stream "/^dev:.*/"`
